---
title: "Contenu clés et objectifs d’apprentissage"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    theme: cosmo
    highlight: tango
---
###Cours 1 - 20 septembre
* Présentation Brise-Glace
* Jeunesse des Loups-Garous : langage familier / le mot phonétique (1)
* Courriel : registre informel / standard / formel

###Cours 2 - 04 octobre
* Comprendre et résumer une conférence : un exemple tiré de TedX Paris 
le mot phonétique (2)
* A faire : Observer une place + prendre un de ses cours en sketchnote

###Cours 3 - 11 octobre
* Prise de notes : quelques astuces
* Au bout de combien de temps est-on vraiment en retard ?
** Comprendre un texte à l'aide de questions et le résumer
** Discuter des dimensions interculturelles
* A faire : lire le texte méthodologique concernant le résumé

###Cours 4 - 15 octobre
* S'exercer au résumé
* Vocabulaire : la synonymie
* CO : ma thèse en 180 minutes

###Cours 5 - 18 octobre
* Débattre : techniques et thématiques ; qu'est-ce qui fait débattre les Français ?
* Langue : les modes subjonctif et conditionnel pour exprimer et nuancer son opinion

###Cours 6 - 05 novembre
* Méthodologie : la synthèse ; entraînement
* CO : extrait de conférence

###Cours 7 - 8 novembre
* Méthodologie : la dissertation
* Débattre

###Cours 8 - 19 novembre
* Contenu à définir
* Langue : décrire de manière fine une situation

###Cours 9 - 29 novembre
* **_Compte-rendu oral de sa lecture (en binôme) - 5 groupes_**
* CO

###Cours 10 - 6 décembre
* **_Compte-rendu oral de sa lecture (en binôme) - 5 groupes_**
* Débattre

###Cours 11 - 13 décembre
* **_Rendu des compte-rendus écrits de la lecture critique_**
* **_Evaluation : résumer d'une conférence_**

###Cours 12 - 20 décembre
* **_Évaluation : synthèse_**


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

